//
// Created by hugoc on 09/06/2021.
//

#ifndef VDSOCKS_V2_ERRORS_H
#define VDSOCKS_V2_ERRORS_H

#define SUCCESS 0
#define FAILURE -1
#define SOCKET_ERROR -1
#define ERROR_MEMORY -100
#define ERROR_OVERFLOW -101
#define ERROR_EVT_ADD_TRIGGER -102
#define ERROR_UNDERFLOW -103
#define ERROR_QUEUE_VIRTUAL_WRITE -104
#define ERROR_SEND -105
#define ERROR_INDEX_RANGE -106
#define ERROR_CLOSE_CONNECTION -107
#define ERROR_FATAL -108
#define ERROR_NULL_POINTER -109

#endif //VDSOCKS_V2_ERRORS_H
